//go:build with_awg

// SIP INVITE request masquerade generator.
//
// This SUPERSEDES the earlier `SIP/2.0 200 OK` response decoy. A 2xx response
// is a server-role packet that only exists in reply to a request; emitting one
// as the client's FIRST, unsolicited packet is a wrong-direction anomaly (the
// same defect the old STUN/DNS profiles had). An INVITE is what a SIP UA
// legitimately sends first to start a call, so it is the RFC-consistent shape
// for a client-initiated decoy — and it carries the headers a 200 OK was
// missing as a flow opener (request-line with the INVITE method, Max-Forwards,
// Contact) plus a realistic SDP offer.
//
// Device status. On the LTE/WARP DPI this feature targets, the sibling DNS/STUN
// profiles are blocked as a protocol CLASS toward the datacenter WARP edge
// (162.159.x:2408) regardless of packet quality — SIP is expected to behave the
// same (SIP lives on a SIP server / :5060, not a datacenter edge). NOT
// device-confirmed for WARP — use ip=quic for WARP. ip=sip is kept for other
// providers whose DPI only checks well-formedness.
//
// RANDOMIZATION (hybrid, no cross-user signature):
//   - Pronounceable user names and (when id is empty) the host are generated by
//     PseudoGen at build time and baked into the static <b> bytes — pronounceable
//     strings cannot come from the CPS <rc> tag (which emits raw letters). They
//     are fresh per generation (crypto/rand), unique between users.
//   - Per-packet volatile tokens (Via branch, From tag, Call-ID, CSeq number,
//     SDP session-id/version) are <rc>/<rd> runs of FIXED width — fresh on every
//     packet, and fixed width keeps Content-Length exact.
//
// The host is either the LDH-validated id (when set) or PseudoGen.pgHost(); a
// validated id cannot inject CRLF, and pgHost() emits only LDH/IP characters.
package wireguard

import (
	"fmt"
	"strings"
)

const (
	sipSDPSessIDLen  = 10 // <rd 10> — o= session-id
	sipSDPSessVerLen = 10 // <rd 10> — o= session-version
)

// masqueSIPInviteCPS builds a SIP INVITE request with an SDP offer. domain may
// be "" — then a pseudo host is generated. Pronounceable user/host are baked
// into <b>; volatile tokens are per-packet <rc>/<rd> of fixed width, so
// Content-Length (over the SDP body) stays exact.
func masqueSIPInviteCPS(domain string) (string, error) {
	host := strings.TrimSuffix(domain, ".")
	if host == "" {
		host = pgHost()
	}
	fromUser := pgUser()
	toUser := pgUser()
	mediaIP := pgPublicIP()

	// Build the SDP body first to get its exact byte length. The two <rd 10>
	// runs are fixed width, and mediaIP is baked here, so len(sdp*) is exact.
	sdpPre := "v=0\r\n" + "o=" + fromUser + " " // ‖ <rd 10> session-id
	sdpMid := " "                               // ‖ <rd 10> session-version
	sdpPost := " IN IP4 " + mediaIP + "\r\n" +
		"s=-\r\n" +
		"c=IN IP4 " + mediaIP + "\r\n" +
		"t=0 0\r\n" +
		"m=audio 49170 RTP/AVP 0 8 101\r\n" +
		"a=rtpmap:0 PCMU/8000\r\n" +
		"a=rtpmap:8 PCMA/8000\r\n" +
		"a=rtpmap:101 telephone-event/8000\r\n" +
		"a=sendrecv\r\n"
	sdpLen := len(sdpPre) + sipSDPSessIDLen + len(sdpMid) + sipSDPSessVerLen + len(sdpPost)

	var b cpsBuilder
	// Request-line (INVITE method, not a status line) + Via up to the branch.
	b.addBytes([]byte("INVITE sip:" + toUser + "@" + host + " SIP/2.0\r\n" +
		"Via: SIP/2.0/UDP " + host + ":5060;branch=z9hG4bK"))
	b.addRandChars(16) // branch token (per-packet)
	b.addBytes([]byte(";rport\r\n" +
		"Max-Forwards: 70\r\n" +
		"From: <sip:" + fromUser + "@" + host + ">;tag="))
	b.addRandChars(12) // From tag (per-packet)
	b.addBytes([]byte("\r\n" +
		"To: <sip:" + toUser + "@" + host + ">\r\n" + // initial INVITE: To has no tag
		"Call-ID: "))
	b.addRandChars(20) // Call-ID local part (per-packet)
	b.addBytes([]byte("@" + host + "\r\n" +
		"CSeq: "))
	b.addRandDigits(4) // CSeq number (per-packet)
	b.addBytes([]byte(" INVITE\r\n" +
		"Contact: <sip:" + fromUser + "@" + host + ":5060>\r\n" +
		"Content-Type: application/sdp\r\n" +
		fmt.Sprintf("Content-Length: %d\r\n", sdpLen) +
		"\r\n"))

	// SDP body: static around the two fixed-width random runs.
	b.addBytes([]byte(sdpPre))
	b.addRandDigits(sipSDPSessIDLen)
	b.addBytes([]byte(sdpMid))
	b.addRandDigits(sipSDPSessVerLen)
	b.addBytes([]byte(sdpPost))

	return b.String(), nil
}
