//go:build with_lx_command

package lxd

import (
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"os"
	"path/filepath"

	E "github.com/sagernet/sing/common/exceptions"
)

// DaemonConfig is the daemon's own base configuration, living in ITS state
// directory (<state-dir>/daemon.json, 0600) — not in the service unit and not
// in any client's directory. The service plist then degenerates to
// `sing-box lxd --state-dir <dir>`: changing the listen address or the secret
// is a file edit + restart, not a service reinstall, and the Bearer secret is
// owned by the daemon (root) instead of leaking into a launcher-owned file
// (SPEC 057: the secret is the daemon's credential, so the daemon keeps it).
//
// Explicit CLI flags still win over the file — the file only fills in what the
// command line left unset, so dev invocations (`sing-box lxd --listen …`)
// behave exactly as typed.
type DaemonConfig struct {
	// Listen is the control channel address (host:port).
	Listen string `json:"listen,omitempty"`
	// TLS enables the mTLS control plane with client enrollment.
	TLS bool `json:"tls,omitempty"`
	// Secret is the Bearer secret for the operator routes (and the only gate
	// when TLS is off). Generated by the daemon on install when absent.
	Secret string `json:"secret,omitempty"`
}

const daemonConfigFile = "daemon.json"

func daemonConfigPath(stateDir string) string {
	return filepath.Join(stateDir, daemonConfigFile)
}

// LoadDaemonConfig reads <stateDir>/daemon.json. Absence is not an error:
// (zero, false, nil) — callers fall back to flag defaults. A present but
// unreadable/corrupt file IS an error: silently ignoring it would boot the
// daemon with a different address/secret than the operator configured.
func LoadDaemonConfig(stateDir string) (DaemonConfig, bool, error) {
	content, found, err := readOptional(daemonConfigPath(stateDir))
	if err != nil || !found {
		return DaemonConfig{}, false, err
	}
	var config DaemonConfig
	if err = json.Unmarshal([]byte(content), &config); err != nil {
		return DaemonConfig{}, false, E.Cause(err, "parse ", daemonConfigFile)
	}
	return config, true, nil
}

// SaveDaemonConfig persists daemon.json atomically with 0600 (the file holds
// the Bearer secret), creating the state directory (0700) when needed.
func SaveDaemonConfig(stateDir string, config DaemonConfig) error {
	stateStore, err := newStore(stateDir)
	if err != nil {
		return err
	}
	encoded, err := json.MarshalIndent(config, "", "  ")
	if err != nil {
		return err
	}
	return stateStore.writeAtomic(daemonConfigPath(stateDir), append(encoded, '\n'))
}

// GenerateSecret returns a fresh Bearer secret: 32 random bytes, lowercase
// hex. Brute force over the network is hopeless; the value lives only in
// daemon.json (0600, daemon-owned).
func GenerateSecret() (string, error) {
	var buf [32]byte
	if _, err := rand.Read(buf[:]); err != nil {
		return "", E.Cause(err, "generate secret")
	}
	return hex.EncodeToString(buf[:]), nil
}

// FindServiceStateDir returns the state directory of an installed service:
// the first scope (system, then user) whose daemon.json exists. found=false
// when neither scope has one. Used by the `client` subcommands and uninstall
// paths so `sudo sing-box lxd client add` works with no flags on a host with
// an installed service.
func FindServiceStateDir() (string, bool) {
	for _, user := range []bool{false, true} {
		dir := DefaultServiceStateDir(user)
		if _, err := os.Stat(daemonConfigPath(dir)); err == nil {
			return dir, true
		}
	}
	return "", false
}
